### ISSUE TITLE
ImportError: No module named _pcan_module

### ISSUE THREAD

**Issue by mengtangli** [RobotnikAutomation/pcan_python#2]
Beginner to ROS and trying to use the ros barrett_hand pkg. 
Installed pcan_python from https://github.com/RobotnikAutomation/pcan_python and the other 4 external dependencies: gcc, swig, python2.7 and peak-linux-driver-7.14 from http://peak-system.com

Tried this command to launch the controller:$ roslaunch bhand_controller bhand_controller.launch

Resultes (part) are:
Traceback (most recent call last):
  File "/home/mengtangli/catkin_ws/src/barrett_hand-hydro-devel/bhand_controller/src/bhand_controller/bhand_node.py", line 35, in <module>
    from pyHand_api import *
  File "/home/mengtangli/catkin_ws/src/barrett_hand-hydro-devel/bhand_controller/src/bhand_controller/pyHand_api.py", line 43, in <module>
    from pcan_python.pcan_library import *
  File "/usr/local/lib/python2.7/dist-packages/pcan_python-0.1dev-py2.7.egg/pcan_python/pcan_library.py", line 35, in <module>
    from pcan_python import pcan_module
  File "/usr/local/lib/python2.7/dist-packages/pcan_python-0.1dev-py2.7.egg/pcan_python/pcan_module.py", line 26, in <module>
    _pcan_module = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pcan_python-0.1dev-py2.7.egg/pcan_python/pcan_module.py", line 18, in swig_import_helper
    import _pcan_module
ImportError: No module named _pcan_module
[bhand_node-2] process has died [pid 4595, exit code 1, cmd /home/mengtangli/catkin_ws/src/barrett_hand-hydro-devel/bhand_controller/src/bhand_controller/bhand_node.py __name:=bhand_node __log:=/home/mengtangli/.ros/log/0f804248-df98-11e4-be3e-001fc644c068/bhand_node-2.log].
log file: /home/mengtangli/.ros/log/0f804248-df98-11e4-be3e-001fc644c068/bhand_node-2*.log

**Comment by RomanRobotnik** [comment]
Hi,

Did you set the $PYTHONPATH variable?

export PYTHONPATH=/usr/lib:$PYTHONPATH

Regards,

-------------------------------------
Román Navarro García
R&D Department
-----------------------------------------------------------------------------------------------------------------
Robotnik Automation, SLL                  Tel: (+34) 963383835
C/Berni y Catala, 53 bajo                    http://www.robotnik.eu
<http://www.robotnik.es/>
46019 - VALENCIA - SPAIN              rnavarro@robotnik.es
-----------------------------------------------------------------------------------------------------------------
Follow us:

[image: Facebook] <https://www.facebook.com/Robotnik.Automation>  [image:
Youtube] <https://www.youtube.com/user/RobotnikRobots>  [image: Linkedin]
<http://www.linkedin.com/company/robotnik-automation-sll>  [image: Twitter]
<https://twitter.com/RobotnikRobots>                [image: www.robotnik.es]
<http://www.robotnik.es/>
-----------------------------------------------------------------------------------------------------------------
-   Aviso legal <http://www.robotnik.es/politica-de-privacidad/> / Privacy
policy <http://www.robotnik.eu/privacy-policy/>    -

2015-04-10 22:41 GMT+02:00 mengtangli <notifications@github.com>:

**Comment by mengtangli** [comment]
Hi,

Thanks for answering. I did set the $PYTHONPATH variable.
I followed the instruction from https://github.com/RobotnikAutomation/pcan_python: 
    $ cd pcan_python-master
    $ make
    $ sudo make install
    $ export PYTHONPATH=/usr/lib:$PYTHONPATH

However, i saw some lines contain /usr/local/lib/.
Does that mean by default the module will be installed in /usr/local/lib instead of /usr/lib/ according to the page? And therefore I should change the path of setting $PYTHONPATH variable?

Best Regards,
Mengtang

**Comment by yunjoo88** [comment]
Hello,
I am stuck in the same problem.
Have you solved it? If yes, how did you do it?
Your comments will be really helpful. Thank you.

**Comment by mengtangli** [comment]
sorry to reply so late. well, this problem is fixed by setting the PYTHONPATH variable to include /usr/lib.
At least it works for me. Hope it helps.

**Comment by RomanRobotnik** [comment]
Thanks for the information!
