### ISSUE TITLE
PCan::Read: error in LINUX_CAN_Read

### ISSUE THREAD

**Issue by anaceri** [RobotnikAutomation/pcan_python#3]
https://github.com/RobotnikAutomation/pcan_python/blob/43d452d6fcb75d4e0c70904c907cf2672e2f0aa0/src/pcan_module.c#L172

we got the barretthand working on Ubuntu xenial 16.04 using ros-kinetic and communication achieved through pcan driven by peak-linux version 8.5.1. When running the command `rosservice call /bhand_node/actions "action: 1"` , as in [ros example](http://wiki.ros.org/barrett_hand), the hand works but we got the following error printed continuously: 
`PCan::Read: error in LINUX_CAN_Read, iRet=11 err=11 ` 
Any idea  what is about and whether this increase the risk to harm the hardware?

**Comment by RomanRobotnik** [comment]
Hi,

Thanks for the report.

This error shouldn't affect the correct functionality of the hardware. It is a minor error in the bus.

Regards,

**Comment by anaceri** [comment]
Thx for the reply!
